package store

import (
	"bytes"
	"encoding/hex"
	"strconv"
	"testing"
)

const objectVectorFile = "testdata/vectors/objects.json"

// vectorCK is the published stand-in for a library content key. A real one is
// 32 random bytes; this one is in the spec so every derived value below is
// reproducible.
var vectorCK = []byte("silo test content key, not secret")

type objectVectorDoc struct {
	Format      string            `json:"format"`
	Note        string            `json:"note"`
	ContentKey  string            `json:"content_key_utf8"`
	Chunks      []chunkSealVector `json:"chunk_seal"`
	Manifests   []manifestVector  `json:"manifest"`
	Directories []objectVector    `json:"directory"`
	Commits     []objectVector    `json:"commit"`
}

// objectVector pins a directory or commit whose fields are literals rather
// than generated: the description is in the spec, and the bytes are here.
type objectVector struct {
	Name       string `json:"name"`
	Sealed     bool   `json:"sealed"`
	EncodedLen int    `json:"encoded_len"`
	Encoded    string `json:"encoded_hex"`
	ObjectID   string `json:"object_id"`
}

type chunkSealVector struct {
	Name          string      `json:"name"`
	Input         inputVector `json:"input"`
	PlaintextHash string      `json:"plaintext_hash"`
	FrameLen      int         `json:"frame_len"`
	FrameSHA256   string      `json:"frame_sha256"`
	ID            string      `json:"id"`
}

type manifestVector struct {
	Name       string      `json:"name"`
	Sealed     bool        `json:"sealed"`
	Input      inputVector `json:"input"`
	ChunkCount int         `json:"chunk_count"`
	EncodedLen int         `json:"encoded_len"`
	Encoded    string      `json:"encoded_hex,omitempty"`
	ObjectID   string      `json:"object_id"`
}

// vectorManifest builds the manifest a client would write for the described
// input, in the named library type — chunking under that type's seed, and
// encrypting first when sealed.
func vectorManifest(t *testing.T, in inputVector, sealed bool) *Manifest {
	t.Helper()
	data := in.bytes()
	m := &Manifest{FileSize: int64(len(data))}
	if Inlined(m.FileSize) {
		m.Inline = data
		return m
	}
	seed := PlainSeed()
	if sealed {
		seed = ChunkerSeed(vectorCK)
	}
	for _, ch := range chunkAll(t, DefaultParams(seed), data) {
		ref := ChunkRef{ID: ChunkID(ch.Data), Size: int64(len(ch.Data))}
		if sealed {
			sc, err := SealChunk(vectorCK, ch.Data)
			if err != nil {
				t.Fatal(err)
			}
			ref.ID, ref.PlaintextHash = sc.ID, sc.PlaintextHash
		}
		m.Chunks = append(m.Chunks, ref)
	}
	return m
}

func buildObjectVectors(t *testing.T) objectVectorDoc {
	t.Helper()
	doc := objectVectorDoc{
		Format: "silo/store/vectors/v1",
		Note: "Generated by go test ./store -run TestObjectVectors -update. Inputs are " +
			"described as in chunker.json. content_key_utf8 is the library content key as " +
			"literal ASCII. encoded_hex is present where the object is small enough to " +
			"compare byte for byte; where it is not, object_id serves.",
		ContentKey: string(vectorCK),
	}

	for _, in := range []inputVector{
		{"pseudorandom", "silo/vector/empty", 0},
		{"pseudorandom", "silo/vector/onebyte", 1},
		{"pseudorandom", "silo/vector/small", 1000},
		{"zeros", "", 1 << 20},
		{"pseudorandom", "silo/vector/random", 1 << 20},
	} {
		plain := in.bytes()
		sc, err := SealChunk(vectorCK, plain)
		if err != nil {
			t.Fatal(err)
		}
		doc.Chunks = append(doc.Chunks, chunkSealVector{
			Name:          in.Generator + "-" + strconv.Itoa(in.Length),
			Input:         in,
			PlaintextHash: sc.PlaintextHash.String(),
			FrameLen:      len(sc.Frame),
			FrameSHA256:   ObjectID(sc.Frame).String(),
			ID:            sc.ID.String(),
		})
	}

	for _, c := range []struct {
		name   string
		in     inputVector
		sealed bool
	}{
		{"empty-plain", inputVector{"pseudorandom", "silo/vector/empty", 0}, false},
		{"empty-sealed", inputVector{"pseudorandom", "silo/vector/empty", 0}, true},
		{"inline-plain", inputVector{"pseudorandom", "silo/vector/small", 1000}, false},
		{"inline-sealed", inputVector{"pseudorandom", "silo/vector/small", 1000}, true},
		{"threshold-minus-one-plain", inputVector{"pseudorandom", "silo/vector/edge", InlineThreshold - 1}, false},
		{"threshold-plain", inputVector{"pseudorandom", "silo/vector/edge", InlineThreshold}, false},
		{"threshold-sealed", inputVector{"pseudorandom", "silo/vector/edge", InlineThreshold}, true},
		{"chunked-16MiB-plain", inputVector{"pseudorandom", "silo/vector/random", 16 << 20}, false},
		{"chunked-16MiB-sealed", inputVector{"pseudorandom", "silo/vector/random", 16 << 20}, true},
	} {
		m := vectorManifest(t, c.in, c.sealed)
		var encoded []byte
		var err error
		if c.sealed {
			encoded, err = m.EncodeSealed(vectorCK)
		} else {
			encoded, err = m.Encode()
		}
		if err != nil {
			t.Fatalf("%s: %v", c.name, err)
		}
		v := manifestVector{
			Name:       c.name,
			Sealed:     c.sealed,
			Input:      c.in,
			ChunkCount: len(m.Chunks),
			EncodedLen: len(encoded),
			ObjectID:   ObjectID(encoded).String(),
		}
		if len(encoded) <= 4096 {
			v.Encoded = hex.EncodeToString(encoded)
		}
		doc.Manifests = append(doc.Manifests, v)
	}
	for _, sealed := range []bool{false, true} {
		suffix := "-plain"
		if sealed {
			suffix = "-sealed"
		}
		doc.Directories = append(doc.Directories,
			encodedVector(t, "empty"+suffix, sealed, encodeDir(&Directory{
				Salt: [DirSaltSize]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
			})),
			encodedVector(t, "three-entries"+suffix, sealed, encodeDir(vectorDir())),
		)
		doc.Commits = append(doc.Commits,
			encodedVector(t, "root-only"+suffix, sealed, encodeCommit(&Commit{Root: id(7)})),
			encodedVector(t, "two-parents"+suffix, sealed, encodeCommit(vectorCommit())),
		)
	}
	return doc
}

// vectorDir and vectorCommit are the fixed structures the directory and
// commit vectors encode. Child ids are byte-repeated so a port can type them
// out; names, modes and timestamps are literals.
func vectorDir() *Directory {
	return &Directory{
		Salt: [DirSaltSize]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
		Entries: []DirEntry{
			{ChildID: id(0xaa), Type: NodeFile, Name: []byte("report.pdf"), Mtime: 1700000000, Mode: 0o644},
			{ChildID: id(0xbb), Type: NodeDir, Name: []byte("photos"), Mtime: 1600000000, Mode: 0o755},
			{ChildID: id(0xcc), Type: NodeSymlink, Name: []byte("current"), Mtime: 1650000000, Mode: 0o777},
		},
	}
}

func vectorCommit() *Commit {
	return &Commit{
		Root:      id(0x42),
		Parents:   []ID{id(0x01), id(0x02)},
		CreatedAt: 1700000000,
		Author:    "vector@silo.invalid",
		Message:   "a commit for the vectors",
	}
}

func encodedVector(t *testing.T, name string, sealed bool, encode func(bool) ([]byte, error)) objectVector {
	t.Helper()
	b, err := encode(sealed)
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	return objectVector{
		Name:       name,
		Sealed:     sealed,
		EncodedLen: len(b),
		Encoded:    hex.EncodeToString(b),
		ObjectID:   ObjectID(b).String(),
	}
}

func encodeDir(d *Directory) func(bool) ([]byte, error) {
	return func(sealed bool) ([]byte, error) {
		if sealed {
			return d.EncodeSealed(vectorCK)
		}
		plain := *d
		plain.Salt = [DirSaltSize]byte{}
		return plain.Encode()
	}
}

func encodeCommit(c *Commit) func(bool) ([]byte, error) {
	return func(sealed bool) ([]byte, error) {
		if sealed {
			return c.EncodeSealed(vectorCK)
		}
		return c.Encode()
	}
}

func TestObjectVectors(t *testing.T) {
	checkVectorFile(t, objectVectorFile, buildObjectVectors(t),
		"every manifest id in every library moves, and porter-mac stops interoperating")
}

// The check a port has to pass: rebuild every object from its description and
// confirm the bytes, then decode the committed hex back and confirm it opens.
func TestObjectVectorsAreReproducibleFromTheFile(t *testing.T) {
	var doc objectVectorDoc
	loadVectors(t, objectVectorFile, &doc)
	ck := []byte(doc.ContentKey)

	for _, v := range doc.Chunks {
		t.Run("chunk/"+v.Name, func(t *testing.T) {
			sc, err := SealChunk(ck, v.Input.bytes())
			if err != nil {
				t.Fatal(err)
			}
			if sc.ID.String() != v.ID || sc.PlaintextHash.String() != v.PlaintextHash ||
				len(sc.Frame) != v.FrameLen || ObjectID(sc.Frame).String() != v.FrameSHA256 {
				t.Fatalf("frame does not match the vector")
			}
		})
	}

	for _, v := range doc.Manifests {
		t.Run("manifest/"+v.Name, func(t *testing.T) {
			m := vectorManifest(t, v.Input, v.Sealed)
			var encoded []byte
			var err error
			if v.Sealed {
				encoded, err = m.EncodeSealed(ck)
			} else {
				encoded, err = m.Encode()
			}
			if err != nil {
				t.Fatal(err)
			}
			if len(m.Chunks) != v.ChunkCount || len(encoded) != v.EncodedLen {
				t.Fatalf("got %d chunks in %d bytes, vector says %d in %d",
					len(m.Chunks), len(encoded), v.ChunkCount, v.EncodedLen)
			}
			if ObjectID(encoded).String() != v.ObjectID {
				t.Fatalf("object id %s, vector says %s", ObjectID(encoded), v.ObjectID)
			}
			if v.Encoded != "" && hex.EncodeToString(encoded) != v.Encoded {
				t.Fatal("encoded bytes differ from the vector")
			}
			if v.Sealed {
				if _, err := DecodeSealedManifest(encoded, ck); err != nil {
					t.Fatalf("the vector's own manifest does not open: %v", err)
				}
			} else if _, err := DecodeManifest(encoded); err != nil {
				t.Fatalf("the vector's own manifest does not decode: %v", err)
			}
		})
	}

	// Directory and commit vectors are checked from the bytes alone: decode
	// what the file holds, re-encode it, and require the same object back.
	// That exercises the decoder against bytes this build did not just write.
	for _, v := range doc.Directories {
		t.Run("directory/"+v.Name, func(t *testing.T) {
			raw, err := hex.DecodeString(v.Encoded)
			if err != nil || len(raw) != v.EncodedLen || ObjectID(raw).String() != v.ObjectID {
				t.Fatal("the vector's own bytes do not match its id")
			}
			var d *Directory
			if v.Sealed {
				d, err = DecodeSealedDirectory(raw, ck)
			} else {
				d, err = DecodeDirectory(raw)
			}
			if err != nil {
				t.Fatalf("decode: %v", err)
			}
			again, err := encodeDir(d)(v.Sealed)
			if err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			if !bytes.Equal(again, raw) {
				t.Fatal("re-encoding the decoded directory produced different bytes")
			}
		})
	}
	for _, v := range doc.Commits {
		t.Run("commit/"+v.Name, func(t *testing.T) {
			raw, err := hex.DecodeString(v.Encoded)
			if err != nil || len(raw) != v.EncodedLen || ObjectID(raw).String() != v.ObjectID {
				t.Fatal("the vector's own bytes do not match its id")
			}
			var c *Commit
			if v.Sealed {
				c, err = DecodeSealedCommit(raw, ck)
			} else {
				c, err = DecodeCommit(raw)
			}
			if err != nil {
				t.Fatalf("decode: %v", err)
			}
			again, err := encodeCommit(c)(v.Sealed)
			if err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			if !bytes.Equal(again, raw) {
				t.Fatal("re-encoding the decoded commit produced different bytes")
			}
		})
	}
}
