package store

import (
	"encoding/hex"
	"strings"
	"testing"
)

const nameVectorFile = "testdata/vectors/names.json"

type nameVectorDoc struct {
	Format      string          `json:"format"`
	Note        string          `json:"note"`
	ContentKey  string          `json:"content_key_utf8"`
	Directories []nameDirVector `json:"directories"`
}

type nameDirVector struct {
	Name    string       `json:"name"`
	DirSalt string       `json:"dir_salt"`
	NameKey string       `json:"name_key"`
	Names   []nameVector `json:"names"`
}

type nameVector struct {
	Plaintext     string `json:"plaintext_utf8"`
	PlaintextLen  int    `json:"plaintext_len"`
	PlaintextHex  string `json:"plaintext_hex"`
	CiphertextHex string `json:"ciphertext_hex"`
	URL           string `json:"url"`
}

// The name lengths are chosen around S2V's branch boundary: under sixteen
// bytes the final component is padded and XORed into a doubled accumulator,
// at sixteen and over it is XORed into its own end. Silo's names sit mostly on
// the short side, which is the side the RFC's headline example never
// exercises.
var nameVectorInputs = []string{
	"a",
	"notes.txt",
	strings.Repeat("n", 14),
	strings.Repeat("n", 15),
	strings.Repeat("n", 16),
	strings.Repeat("n", 17),
	strings.Repeat("n", 32),
	strings.Repeat("n", MaxPlainNameBytes),
	"Ünïcödé — naïve.pdf",
}

func buildNameVectors(t *testing.T) nameVectorDoc {
	t.Helper()
	doc := nameVectorDoc{
		Format: "silo/store/vectors/v1",
		Note: "Generated by go test ./store -run TestNameVectors -update. " +
			"name_key = HKDF-SHA256(content_key, salt=\"silo/names/v1\", info=dir_salt, L=64); " +
			"ciphertext = AES-CMAC-SIV (RFC 5297, AES-256 halves) of the name with no " +
			"associated data; url = base64url unpadded of the ciphertext. Directory " +
			"objects carry the raw ciphertext, never the url form. The two directories " +
			"share every name, so the same plaintext under different salts must give " +
			"unrelated ciphertexts.",
		ContentKey: string(vectorCK),
	}

	for _, d := range []struct {
		name string
		salt [DirSaltSize]byte
	}{
		{"salt-a", [DirSaltSize]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}},
		{"salt-b", [DirSaltSize]byte{255, 254, 253, 252, 251, 250, 249, 248, 7, 6, 5, 4, 3, 2, 1, 0}},
	} {
		key, err := NameKey(vectorCK, d.salt)
		if err != nil {
			t.Fatal(err)
		}
		dv := nameDirVector{
			Name:    d.name,
			DirSalt: hex.EncodeToString(d.salt[:]),
			NameKey: hex.EncodeToString(key),
		}
		c, err := NewNameCipher(key)
		if err != nil {
			t.Fatal(err)
		}
		for _, name := range nameVectorInputs {
			ct, err := c.Encrypt(name)
			if err != nil {
				t.Fatalf("%q: %v", name, err)
			}
			dv.Names = append(dv.Names, nameVector{
				Plaintext:     name,
				PlaintextLen:  len(name),
				PlaintextHex:  hex.EncodeToString([]byte(name)),
				CiphertextHex: hex.EncodeToString(ct),
				URL:           NameToURL(ct),
			})
		}
		doc.Directories = append(doc.Directories, dv)
	}
	return doc
}

func TestNameVectors(t *testing.T) {
	checkVectorFile(t, nameVectorFile, buildNameVectors(t),
		"every entry name in every E2EE library re-encrypts, so every directory object id moves")
}

// What a port has to pass: derive the key from the committed salt, reproduce
// every ciphertext, and open the committed ciphertexts back to their names.
func TestNameVectorsAreReproducibleFromTheFile(t *testing.T) {
	var doc nameVectorDoc
	loadVectors(t, nameVectorFile, &doc)
	ck := []byte(doc.ContentKey)

	for _, d := range doc.Directories {
		t.Run(d.Name, func(t *testing.T) {
			saltBytes := mustHex(t, d.DirSalt)
			var salt [DirSaltSize]byte
			copy(salt[:], saltBytes)
			key, err := NameKey(ck, salt)
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(key) != d.NameKey {
				t.Fatalf("derived name key %s, vector says %s", hex.EncodeToString(key), d.NameKey)
			}
			c, err := NewNameCipher(key)
			if err != nil {
				t.Fatal(err)
			}
			for _, n := range d.Names {
				ct, err := c.Encrypt(n.Plaintext)
				if err != nil {
					t.Fatalf("%q: %v", n.Plaintext, err)
				}
				if hex.EncodeToString(ct) != n.CiphertextHex {
					t.Fatalf("%q encrypted to %s, vector says %s",
						n.Plaintext, hex.EncodeToString(ct), n.CiphertextHex)
				}
				if NameToURL(ct) != n.URL {
					t.Fatalf("%q rendered to %s, vector says %s", n.Plaintext, NameToURL(ct), n.URL)
				}
				got, err := c.Decrypt(mustHex(t, n.CiphertextHex))
				if err != nil || got != n.Plaintext {
					t.Fatalf("the vector's own ciphertext opened to %q (%v)", got, err)
				}
			}
		})
	}

	// The two directories share every name, so no ciphertext may appear in
	// both — that is the equality leak the per-directory key closes.
	seen := map[string]string{}
	for _, d := range doc.Directories {
		for _, n := range d.Names {
			if prev, ok := seen[n.CiphertextHex]; ok {
				t.Fatalf("%s and %s produced the same ciphertext for %q", prev, d.Name, n.Plaintext)
			}
			seen[n.CiphertextHex] = d.Name
		}
	}
}
