package store

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

const objectVectorFile = "testdata/vectors/objects.json"

// vectorCK is the published stand-in for a library content key. A real one is
// 32 random bytes; this one is in the spec so every derived value below is
// reproducible.
var vectorCK = []byte("silo test content key, not secret")

type objectVectorDoc struct {
	Format     string            `json:"format"`
	Note       string            `json:"note"`
	ContentKey string            `json:"content_key_utf8"`
	Chunks     []chunkSealVector `json:"chunk_seal"`
	Manifests  []manifestVector  `json:"manifest"`
}

type chunkSealVector struct {
	Name          string      `json:"name"`
	Input         inputVector `json:"input"`
	PlaintextHash string      `json:"plaintext_hash"`
	FrameLen      int         `json:"frame_len"`
	FrameSHA256   string      `json:"frame_sha256"`
	ID            string      `json:"id"`
}

type manifestVector struct {
	Name       string      `json:"name"`
	Sealed     bool        `json:"sealed"`
	Input      inputVector `json:"input"`
	ChunkCount int         `json:"chunk_count"`
	EncodedLen int         `json:"encoded_len"`
	Encoded    string      `json:"encoded_hex,omitempty"`
	ObjectID   string      `json:"object_id"`
}

// vectorManifest builds the manifest a client would write for the described
// input, in the named library type — chunking under that type's seed, and
// encrypting first when sealed.
func vectorManifest(t *testing.T, in inputVector, sealed bool) *Manifest {
	t.Helper()
	data := in.bytes()
	m := &Manifest{FileSize: int64(len(data))}
	if Inlined(m.FileSize) {
		m.Inline = data
		return m
	}
	seed := PlainSeed()
	if sealed {
		seed = ChunkerSeed(vectorCK)
	}
	for _, ch := range chunkAll(t, DefaultParams(seed), data) {
		ref := ChunkRef{ID: ChunkID(ch.Data), Size: int64(len(ch.Data))}
		if sealed {
			sc, err := SealChunk(vectorCK, ch.Data)
			if err != nil {
				t.Fatal(err)
			}
			ref.ID, ref.PlaintextHash = sc.ID, sc.PlaintextHash
		}
		m.Chunks = append(m.Chunks, ref)
	}
	return m
}

func buildObjectVectors(t *testing.T) objectVectorDoc {
	t.Helper()
	doc := objectVectorDoc{
		Format: "silo/store/vectors/v1",
		Note: "Generated by go test ./store -run TestObjectVectors -update. Inputs are " +
			"described as in chunker.json. content_key_utf8 is the library content key as " +
			"literal ASCII. encoded_hex is present where the object is small enough to " +
			"compare byte for byte; where it is not, object_id serves.",
		ContentKey: string(vectorCK),
	}

	for _, in := range []inputVector{
		{"pseudorandom", "silo/vector/empty", 0},
		{"pseudorandom", "silo/vector/onebyte", 1},
		{"pseudorandom", "silo/vector/small", 1000},
		{"zeros", "", 1 << 20},
		{"pseudorandom", "silo/vector/random", 1 << 20},
	} {
		plain := in.bytes()
		sc, err := SealChunk(vectorCK, plain)
		if err != nil {
			t.Fatal(err)
		}
		doc.Chunks = append(doc.Chunks, chunkSealVector{
			Name:          in.Generator + "-" + itoa(in.Length),
			Input:         in,
			PlaintextHash: sc.PlaintextHash.String(),
			FrameLen:      len(sc.Frame),
			FrameSHA256:   ObjectID(sc.Frame).String(),
			ID:            sc.ID.String(),
		})
	}

	for _, c := range []struct {
		name   string
		in     inputVector
		sealed bool
	}{
		{"empty-plain", inputVector{"pseudorandom", "silo/vector/empty", 0}, false},
		{"empty-sealed", inputVector{"pseudorandom", "silo/vector/empty", 0}, true},
		{"inline-plain", inputVector{"pseudorandom", "silo/vector/small", 1000}, false},
		{"inline-sealed", inputVector{"pseudorandom", "silo/vector/small", 1000}, true},
		{"threshold-minus-one-plain", inputVector{"pseudorandom", "silo/vector/edge", InlineThreshold - 1}, false},
		{"threshold-plain", inputVector{"pseudorandom", "silo/vector/edge", InlineThreshold}, false},
		{"threshold-sealed", inputVector{"pseudorandom", "silo/vector/edge", InlineThreshold}, true},
		{"chunked-16MiB-plain", inputVector{"pseudorandom", "silo/vector/random", 16 << 20}, false},
		{"chunked-16MiB-sealed", inputVector{"pseudorandom", "silo/vector/random", 16 << 20}, true},
	} {
		m := vectorManifest(t, c.in, c.sealed)
		var encoded []byte
		var err error
		if c.sealed {
			encoded, err = m.EncodeSealed(vectorCK)
		} else {
			encoded, err = m.Encode()
		}
		if err != nil {
			t.Fatalf("%s: %v", c.name, err)
		}
		v := manifestVector{
			Name:       c.name,
			Sealed:     c.sealed,
			Input:      c.in,
			ChunkCount: len(m.Chunks),
			EncodedLen: len(encoded),
			ObjectID:   ObjectID(encoded).String(),
		}
		if len(encoded) <= 4096 {
			v.Encoded = hex.EncodeToString(encoded)
		}
		doc.Manifests = append(doc.Manifests, v)
	}
	return doc
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}

func TestObjectVectors(t *testing.T) {
	encoded, err := json.MarshalIndent(buildObjectVectors(t), "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	encoded = append(encoded, '\n')

	if *updateVectors {
		if err := os.WriteFile(objectVectorFile, encoded, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", objectVectorFile, len(encoded))
		return
	}
	want, err := os.ReadFile(objectVectorFile)
	if err != nil {
		t.Fatalf("reading vectors: %v (regenerate with -update)", err)
	}
	if string(encoded) != string(want) {
		t.Fatalf("this build no longer reproduces %s.\n"+
			"That is a format change: every manifest id in every library moves, "+
			"and porter-mac stops interoperating. If it is deliberate, "+
			"regenerate with -update and review the diff.", objectVectorFile)
	}
}

// The check a port has to pass: rebuild every object from its description and
// confirm the bytes, then decode the committed hex back and confirm it opens.
func TestObjectVectorsAreReproducibleFromTheFile(t *testing.T) {
	raw, err := os.ReadFile(objectVectorFile)
	if err != nil {
		t.Fatal(err)
	}
	var doc objectVectorDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	ck := []byte(doc.ContentKey)

	for _, v := range doc.Chunks {
		t.Run("chunk/"+v.Name, func(t *testing.T) {
			sc, err := SealChunk(ck, v.Input.bytes())
			if err != nil {
				t.Fatal(err)
			}
			if sc.ID.String() != v.ID || sc.PlaintextHash.String() != v.PlaintextHash ||
				len(sc.Frame) != v.FrameLen || ObjectID(sc.Frame).String() != v.FrameSHA256 {
				t.Fatalf("frame does not match the vector")
			}
		})
	}

	for _, v := range doc.Manifests {
		t.Run("manifest/"+v.Name, func(t *testing.T) {
			m := vectorManifest(t, v.Input, v.Sealed)
			var encoded []byte
			var err error
			if v.Sealed {
				encoded, err = m.EncodeSealed(ck)
			} else {
				encoded, err = m.Encode()
			}
			if err != nil {
				t.Fatal(err)
			}
			if len(m.Chunks) != v.ChunkCount || len(encoded) != v.EncodedLen {
				t.Fatalf("got %d chunks in %d bytes, vector says %d in %d",
					len(m.Chunks), len(encoded), v.ChunkCount, v.EncodedLen)
			}
			if ObjectID(encoded).String() != v.ObjectID {
				t.Fatalf("object id %s, vector says %s", ObjectID(encoded), v.ObjectID)
			}
			if v.Encoded != "" && hex.EncodeToString(encoded) != v.Encoded {
				t.Fatal("encoded bytes differ from the vector")
			}
			if v.Sealed {
				if _, err := DecodeSealedManifest(encoded, ck); err != nil {
					t.Fatalf("the vector's own manifest does not open: %v", err)
				}
			} else if _, err := DecodeManifest(encoded); err != nil {
				t.Fatalf("the vector's own manifest does not decode: %v", err)
			}
		})
	}
}
