package store

import (
	"bytes"
	"crypto/ecdh"
	"encoding/hex"
	"strings"
	"testing"
)

const keyVectorFile = "testdata/vectors/keys.json"

type keyVectorDoc struct {
	Format          string               `json:"format"`
	Note            string               `json:"note"`
	Bounds          kdfBoundsVector      `json:"kdf_bounds"`
	KDF             []kdfVector          `json:"kdf"`
	KDFRefused      []kdfRefusedVector   `json:"kdf_refused"`
	Identities      []identityVector     `json:"identities"`
	IdentityWraps   []identityWrapVector `json:"identity_wraps"`
	ContentKeyWraps []ckWrapVector       `json:"content_key_wraps"`
	RecoveryCodes   []recoveryVector     `json:"recovery_codes"`
	RecoveryWraps   []recoveryWrapVector `json:"recovery_wraps"`
}

// The floor and ceiling as numbers, so a port checks against the same bytes
// rather than against a sentence in the spec.
type kdfBoundsVector struct {
	MinMemoryKiB uint32 `json:"min_memory_kib"`
	MaxMemoryKiB uint32 `json:"max_memory_kib"`
	MinTime      uint32 `json:"min_time"`
	MaxTime      uint32 `json:"max_time"`
	MinLanes     uint8  `json:"min_lanes"`
	MaxLanes     uint8  `json:"max_lanes"`
	Default      string `json:"default_params"`
}

type kdfVector struct {
	Name     string `json:"name"`
	Password string `json:"password_utf8"`
	Params   string `json:"params"`
	AuthKey  string `json:"auth_key_hex"`
	WrapKey  string `json:"wrap_key_hex"`
}

// The rejection vectors. Without these a port that omits the floor check
// passes every other vector in this file, which is exactly the failure mode
// the floor exists to prevent.
type kdfRefusedVector struct {
	Name      string `json:"name"`
	Params    string `json:"params"`
	RefusedAt string `json:"refused_at"` // "parse" or "bounds"
	Why       string `json:"why"`
}

type identityVector struct {
	Name    string `json:"name"`
	Private string `json:"private_hex"`
	Public  string `json:"public_hex"`
}

type identityWrapVector struct {
	Name     string `json:"name"`
	WrapKey  string `json:"wrap_key_hex"`
	Holder   string `json:"holder"`
	Params   string `json:"params"`
	WrapSalt string `json:"wrap_salt_hex"`
	Private  string `json:"private_hex"`
	Blob     string `json:"blob_hex"`
}

type ckWrapVector struct {
	Name         string `json:"name"`
	EphemeralKey string `json:"ephemeral_private_hex"`
	RecipientKey string `json:"recipient_private_hex"`
	RecipientPub string `json:"recipient_public_hex"`
	Library      string `json:"library"`
	ContentKey   string `json:"content_key_hex"`
	Blob         string `json:"blob_hex"`
}

type recoveryVector struct {
	Name       string `json:"name"`
	Input      string `json:"input"`
	Normalized string `json:"normalized"`
	Display    string `json:"display"`
	Secret     string `json:"secret_hex"`
}

type recoveryWrapVector struct {
	Name     string `json:"name"`
	Code     string `json:"code"`
	Holder   string `json:"holder"`
	WrapSalt string `json:"wrap_salt_hex"`
	Private  string `json:"private_hex"`
	Blob     string `json:"blob_hex"`
}

// vectorSalt mints a reproducible salt. It serves both the KDF salt and the
// wrap salt because the two are the same width; should either move, this stops
// compiling at the call sites for the other, which is the right place to find
// out.
func vectorSalt(label string) [KDFSaltSize]byte {
	var s [KDFSaltSize]byte
	copy(s[:], pseudoRandom(label, KDFSaltSize))
	return s
}

// mustKey decodes a hex field into a fixed-width key. The width is checked
// rather than left to copy, which silently short-fills a truncated field.
func mustKey(t *testing.T, s string) [X25519KeySize]byte {
	t.Helper()
	b := mustHex(t, s)
	if len(b) != X25519KeySize {
		t.Fatalf("%s is %d bytes, want a %d-byte key", s, len(b), X25519KeySize)
	}
	var k [X25519KeySize]byte
	copy(k[:], b)
	return k
}

// vectorSaltFromHex decodes a committed wrap salt.
func vectorSaltFromHex(t *testing.T, s string) [WrapSaltSize]byte {
	t.Helper()
	b := mustHex(t, s)
	if len(b) != WrapSaltSize {
		t.Fatalf("%s is %d bytes, want a %d-byte salt", s, len(b), WrapSaltSize)
	}
	var salt [WrapSaltSize]byte
	copy(salt[:], b)
	return salt
}

func vectorPrivate(t *testing.T, label string) *Identity {
	t.Helper()
	var priv [X25519KeySize]byte
	copy(priv[:], pseudoRandom(label, X25519KeySize))
	id, err := IdentityFromPrivate(priv)
	if err != nil {
		t.Fatal(err)
	}
	return id
}

func buildKeyVectors(t *testing.T) keyVectorDoc {
	t.Helper()
	doc := keyVectorDoc{
		Format: "silo/store/vectors/v1",
		Note: "Generated by go test ./store -run TestKeyVectors -update. " +
			"master = argon2id(password, salt, params); authKey = HKDF-SHA256(master, " +
			"salt=\"silo/auth/v1\", info=\"\", L=32); wrapKey = the same with " +
			"salt=\"silo/wrap/v1\". Wrapped blobs seal a 32-byte X25519 private key or " +
			"content key under AES-256-GCM with a zero nonce, keyed " +
			"HKDF-SHA256(secret, salt=<domain>, info=SHA-256(AD), L=32), where AD is the " +
			"blob from byte 0 up to the ciphertext. The wrap salt and the ephemeral key " +
			"are fresh per wrap in production and fixed here so the bytes can be pinned; " +
			"kdf_refused is the half a port passes every other vector without.",
		Bounds: kdfBoundsVector{
			MinMemoryKiB: MinKDFMemory, MaxMemoryKiB: MaxKDFMemory,
			MinTime: MinKDFTime, MaxTime: MaxKDFTime,
			MinLanes: MinKDFLanes, MaxLanes: MaxKDFLanes,
			Default: DefaultKDFParams(vectorSalt("kdf/default")).String(),
		},
	}

	for _, tc := range []struct {
		name, password string
		p              KDFParams
	}{
		{"default-params", testPassword, DefaultKDFParams(vectorSalt("kdf/default"))},
		{"floor-params", testPassword, floorParams(vectorSalt("kdf/floor"))},
		{"unicode-password", "pässwörd — naïve 🔐", floorParams(vectorSalt("kdf/unicode"))},
		{"empty-password", "", floorParams(vectorSalt("kdf/empty"))},
	} {
		creds, err := DeriveCredentials(tc.password, tc.p)
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		doc.KDF = append(doc.KDF, kdfVector{
			Name:     tc.name,
			Password: tc.password,
			Params:   tc.p.String(),
			AuthKey:  hex.EncodeToString(creds.AuthKey),
			WrapKey:  hex.EncodeToString(creds.WrapKey),
		})
	}

	// The bounds cases are built from the constants rather than typed out, so
	// that "just below the floor" keeps meaning that after the floor is raised.
	// A literal would quietly become "far below the floor", and -update would
	// regenerate the file around it without a word.
	refused := func(m, t uint32, lanes uint8) string {
		return KDFParams{Memory: m, Time: t, Lanes: lanes}.String()
	}
	doc.KDFRefused = []kdfRefusedVector{
		{"memory-below-floor", refused(8, DefaultKDFTime, DefaultKDFLanes), "bounds",
			"argon2's own minimum, and far under this format's floor"},
		{"memory-just-below-floor", refused(MinKDFMemory-1, DefaultKDFTime, DefaultKDFLanes), "bounds",
			"one KiB under the floor; the off-by-one a port is most likely to get wrong"},
		{"time-below-floor", refused(DefaultKDFMemory, MinKDFTime-1, DefaultKDFLanes), "bounds",
			"a single pass"},
		{"lanes-zero", refused(DefaultKDFMemory, DefaultKDFTime, MinKDFLanes-1), "bounds",
			"zero lanes"},
		{"memory-above-ceiling", refused(MaxKDFMemory*2, DefaultKDFTime, DefaultKDFLanes), "bounds",
			"two GiB: not weaker, just a client the server can take down"},
		{"time-above-ceiling", refused(DefaultKDFMemory, MaxKDFTime+1, DefaultKDFLanes), "bounds",
			"above the pass ceiling"},
		{"wrong-algorithm", "$argon2i$v=19$m=65536,t=3,p=4$AAAAAAAAAAAAAAAAAAAAAA", "parse",
			"argon2i is not what this format defines"},
		{"wrong-version", "$argon2id$v=16$m=65536,t=3,p=4$AAAAAAAAAAAAAAAAAAAAAA", "parse",
			"argon2 version 0x10 produces different output for the same parameters"},
		{"reordered-costs", "$argon2id$v=19$t=3,m=65536,p=4$AAAAAAAAAAAAAAAAAAAAAA", "parse",
			"one field order, so the string round-trips byte for byte"},
		{"leading-zero", "$argon2id$v=19$m=65536,t=03,p=4$AAAAAAAAAAAAAAAAAAAAAA", "parse",
			"two spellings of one number is one too many"},
		{"short-salt", "$argon2id$v=19$m=65536,t=3,p=4$AAAAAAAAAAAA", "parse",
			"salt is exactly 16 bytes"},
		{"padded-salt", "$argon2id$v=19$m=65536,t=3,p=4$AAAAAAAAAAAAAAAAAAAAAA==", "parse",
			"unpadded base64, as the PHC string specifies"},
	}

	for _, label := range []string{"identity/a", "identity/b"} {
		id := vectorPrivate(t, label)
		priv, pub := id.Private(), id.Public()
		doc.Identities = append(doc.Identities, identityVector{
			Name:    label,
			Private: hex.EncodeToString(priv[:]),
			Public:  hex.EncodeToString(pub[:]),
		})
	}

	// Identity wraps, with the salt fixed so the blob is reproducible.
	for _, tc := range []struct {
		name, holder string
		p            KDFParams
	}{
		{"default-params", testHolder, DefaultKDFParams(vectorSalt("kdf/default"))},
		{"floor-params", "d@nmilne.com", floorParams(vectorSalt("kdf/floor"))},
	} {
		creds, err := DeriveCredentials(testPassword, tc.p)
		if err != nil {
			t.Fatal(err)
		}
		id := vectorPrivate(t, "identity/a")
		priv := id.Private()
		salt := vectorSalt("wrap/" + tc.name)
		blob, err := wrapSecret(creds.WrapKey, domainWrapIdentity, wrapKindPassword,
			salt, tc.p.String(), tc.holder, priv[:])
		if err != nil {
			t.Fatal(err)
		}
		if got, err := UnwrapIdentity(creds.WrapKey, tc.holder, blob); err != nil || got != priv {
			t.Fatalf("%s: the vector does not open: %v", tc.name, err)
		}
		doc.IdentityWraps = append(doc.IdentityWraps, identityWrapVector{
			Name:     tc.name,
			WrapKey:  hex.EncodeToString(creds.WrapKey),
			Holder:   tc.holder,
			Params:   tc.p.String(),
			WrapSalt: hex.EncodeToString(salt[:]),
			Private:  hex.EncodeToString(priv[:]),
			Blob:     hex.EncodeToString(blob),
		})
	}

	// Content key wraps, with the ephemeral fixed for the same reason.
	for _, tc := range []struct {
		name, library, recipient, ephemeral string
		ck                                  []byte
	}{
		{"member-a", testLibrary, "identity/a", "ephemeral/1",
			pseudoRandom("ck/one", CKSize)},
		{"member-b-same-key", testLibrary, "identity/b", "ephemeral/2",
			pseudoRandom("ck/one", CKSize)},
		{"member-a-other-library", testOtherLibrary, "identity/a", "ephemeral/3",
			pseudoRandom("ck/one", CKSize)},
	} {
		recipient := vectorPrivate(t, tc.recipient)
		ephID := vectorPrivate(t, tc.ephemeral)
		ephPriv := ephID.Private()
		eph, err := ecdh.X25519().NewPrivateKey(ephPriv[:])
		if err != nil {
			t.Fatal(err)
		}
		recipientPub := recipient.Public()
		pub, err := ecdh.X25519().NewPublicKey(recipientPub[:])
		if err != nil {
			t.Fatal(err)
		}
		blob, err := wrapCKWith(eph, pub, tc.library, tc.ck)
		if err != nil {
			t.Fatal(err)
		}
		if got, err := UnwrapCK(recipient, tc.library, blob); err != nil || !bytes.Equal(got, tc.ck) {
			t.Fatalf("%s: the vector does not open: %v", tc.name, err)
		}
		recipientPriv := recipient.Private()
		doc.ContentKeyWraps = append(doc.ContentKeyWraps, ckWrapVector{
			Name:         tc.name,
			EphemeralKey: hex.EncodeToString(ephPriv[:]),
			RecipientKey: hex.EncodeToString(recipientPriv[:]),
			RecipientPub: hex.EncodeToString(recipientPub[:]),
			Library:      tc.library,
			ContentKey:   hex.EncodeToString(tc.ck),
			Blob:         hex.EncodeToString(blob),
		})
	}

	// Recovery codes: one canonical code, then the same code as a person
	// might type it. Every input in a group must normalize to one string.
	canonical := FormatRecoveryCode(crockfordEncode(pseudoRandom("recovery/one", RecoveryCodeSize)))
	for _, tc := range []struct{ name, in string }{
		{"as-printed", canonical},
		{"lower-case", strings.ToLower(canonical)},
		{"no-separators", strings.ReplaceAll(canonical, "-", "")},
		{"spaces-for-hyphens", strings.ReplaceAll(canonical, "-", " ")},
		{"O-for-zero", strings.ReplaceAll(canonical, "0", "O")},
		{"I-for-one", strings.ReplaceAll(canonical, "1", "I")},
		{"lower-l-for-one", strings.ReplaceAll(strings.ToLower(canonical), "1", "l")},
	} {
		normalized, err := NormalizeRecoveryCode(tc.in)
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		secret, err := RecoveryCodeSecret(tc.in)
		if err != nil {
			t.Fatal(err)
		}
		doc.RecoveryCodes = append(doc.RecoveryCodes, recoveryVector{
			Name:       tc.name,
			Input:      tc.in,
			Normalized: normalized,
			Display:    FormatRecoveryCode(normalized),
			Secret:     hex.EncodeToString(secret),
		})
	}

	{
		id := vectorPrivate(t, "identity/a")
		priv := id.Private()
		secret, err := RecoveryCodeSecret(canonical)
		if err != nil {
			t.Fatal(err)
		}
		salt := vectorSalt("wrap/recovery")
		blob, err := wrapSecret(secret, domainWrapRecovery, wrapKindRecovery, salt, "", testHolder, priv[:])
		if err != nil {
			t.Fatal(err)
		}
		if got, err := UnwrapWithRecovery(canonical, testHolder, blob); err != nil || got != priv {
			t.Fatalf("the recovery vector does not open: %v", err)
		}
		doc.RecoveryWraps = append(doc.RecoveryWraps, recoveryWrapVector{
			Name:     "identity-a",
			Code:     canonical,
			Holder:   testHolder,
			WrapSalt: hex.EncodeToString(salt[:]),
			Private:  hex.EncodeToString(priv[:]),
			Blob:     hex.EncodeToString(blob),
		})
	}

	return doc
}

func TestKeyVectors(t *testing.T) {
	checkVectorFile(t, keyVectorFile, buildKeyVectors(t),
		"every wrapped blob on every server becomes unopenable and every account has to re-enrol")
}

// What a port has to pass: derive both halves from the committed parameters,
// open every committed blob, refuse every committed rejection case, and
// normalize every spelling of a recovery code to the same twenty bytes.
func TestKeyVectorsAreReproducibleFromTheFile(t *testing.T) {
	var doc keyVectorDoc
	loadVectors(t, keyVectorFile, &doc)

	t.Run("bounds", func(t *testing.T) {
		if doc.Bounds.MinMemoryKiB != MinKDFMemory || doc.Bounds.MaxMemoryKiB != MaxKDFMemory ||
			doc.Bounds.MinTime != MinKDFTime || doc.Bounds.MaxTime != MaxKDFTime ||
			doc.Bounds.MinLanes != MinKDFLanes || doc.Bounds.MaxLanes != MaxKDFLanes {
			t.Fatalf("the committed bounds are not this build's: %+v", doc.Bounds)
		}
	})

	t.Run("kdf", func(t *testing.T) {
		for _, v := range doc.KDF {
			p, err := ParseKDFParams(v.Params)
			if err != nil {
				t.Fatalf("%s: %v", v.Name, err)
			}
			creds, err := DeriveCredentials(v.Password, p)
			if err != nil {
				t.Fatalf("%s: %v", v.Name, err)
			}
			if got := hex.EncodeToString(creds.AuthKey); got != v.AuthKey {
				t.Errorf("%s auth key %s, vector says %s", v.Name, got, v.AuthKey)
			}
			if got := hex.EncodeToString(creds.WrapKey); got != v.WrapKey {
				t.Errorf("%s wrap key %s, vector says %s", v.Name, got, v.WrapKey)
			}
		}
	})

	t.Run("refused", func(t *testing.T) {
		for _, v := range doc.KDFRefused {
			p, err := ParseKDFParams(v.Params)
			switch v.RefusedAt {
			case "parse":
				if err == nil {
					t.Errorf("%s: parsed, and the vector says it must not", v.Name)
				}
				continue
			case "bounds":
				if err != nil {
					t.Errorf("%s: refused at parse, and the vector says it is refused at the bounds", v.Name)
					continue
				}
				if err := p.Validate(); err == nil {
					t.Errorf("%s: passed the bounds check (%s)", v.Name, v.Why)
				}
				if _, err := DeriveCredentials("hunter2", p); err == nil {
					t.Errorf("%s: derived a key (%s)", v.Name, v.Why)
				}
			default:
				t.Errorf("%s: unknown refused_at %q", v.Name, v.RefusedAt)
			}
		}
	})

	t.Run("identities", func(t *testing.T) {
		for _, v := range doc.Identities {
			priv := mustKey(t, v.Private)
			id, err := IdentityFromPrivate(priv)
			if err != nil {
				t.Fatalf("%s: %v", v.Name, err)
			}
			pub := id.Public()
			if got := hex.EncodeToString(pub[:]); got != v.Public {
				t.Errorf("%s public key %s, vector says %s", v.Name, got, v.Public)
			}
		}
	})

	t.Run("identity-wraps", func(t *testing.T) {
		for _, v := range doc.IdentityWraps {
			wrapKey := mustHex(t, v.WrapKey)
			blob := mustHex(t, v.Blob)

			// The committed blob opens.
			got, err := UnwrapIdentity(wrapKey, v.Holder, blob)
			if err != nil {
				t.Errorf("%s: the committed blob did not open: %v", v.Name, err)
				continue
			}
			if hex.EncodeToString(got[:]) != v.Private {
				t.Errorf("%s: opened to a different key", v.Name)
			}
			// And is reproduced byte for byte from its stated inputs.
			p, err := ParseKDFParams(v.Params)
			if err != nil {
				t.Fatal(err)
			}
			salt := vectorSaltFromHex(t, v.WrapSalt)
			priv := mustKey(t, v.Private)
			rebuilt, err := wrapSecret(wrapKey, domainWrapIdentity, wrapKindPassword,
				salt, p.String(), v.Holder, priv[:])
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(rebuilt) != v.Blob {
				t.Errorf("%s: rebuilt to %s, vector says %s", v.Name, hex.EncodeToString(rebuilt), v.Blob)
			}
			// The holder is bound, not decoration.
			if _, err := UnwrapIdentity(wrapKey, v.Holder+"x", blob); err == nil {
				t.Errorf("%s: opened as the wrong holder", v.Name)
			}
		}
	})

	t.Run("content-key-wraps", func(t *testing.T) {
		for _, v := range doc.ContentKeyWraps {
			priv := mustKey(t, v.RecipientKey)
			recipient, err := IdentityFromPrivate(priv)
			if err != nil {
				t.Fatal(err)
			}
			blob := mustHex(t, v.Blob)
			got, err := UnwrapCK(recipient, v.Library, blob)
			if err != nil {
				t.Errorf("%s: the committed blob did not open: %v", v.Name, err)
				continue
			}
			if hex.EncodeToString(got) != v.ContentKey {
				t.Errorf("%s: opened to a different content key", v.Name)
			}
			if _, err := UnwrapCK(recipient, v.Library+"x", blob); err == nil {
				t.Errorf("%s: opened for the wrong library", v.Name)
			}

			ephPriv := mustKey(t, v.EphemeralKey)
			eph, err := ecdh.X25519().NewPrivateKey(ephPriv[:])
			if err != nil {
				t.Fatal(err)
			}
			pubBytes := mustKey(t, v.RecipientPub)
			pub, err := ecdh.X25519().NewPublicKey(pubBytes[:])
			if err != nil {
				t.Fatal(err)
			}
			rebuilt, err := wrapCKWith(eph, pub, v.Library, mustHex(t, v.ContentKey))
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(rebuilt) != v.Blob {
				t.Errorf("%s: rebuilt to %s, vector says %s", v.Name, hex.EncodeToString(rebuilt), v.Blob)
			}
		}

		// One content key wrapped to two members must give two unrelated
		// blobs, and neither member may open the other's.
		if len(doc.ContentKeyWraps) >= 2 {
			a, b := doc.ContentKeyWraps[0], doc.ContentKeyWraps[1]
			if a.ContentKey != b.ContentKey {
				t.Fatal("the two-member vectors no longer share a content key")
			}
			if a.Blob == b.Blob {
				t.Fatal("one content key wrapped to two members gave one blob")
			}
			priv := mustKey(t, a.RecipientKey)
			alice, err := IdentityFromPrivate(priv)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := UnwrapCK(alice, b.Library, mustHex(t, b.Blob)); err == nil {
				t.Fatal("one member opened another's wrap")
			}
		}
	})

	t.Run("recovery-codes", func(t *testing.T) {
		var secret string
		for _, v := range doc.RecoveryCodes {
			got, err := NormalizeRecoveryCode(v.Input)
			if err != nil {
				t.Errorf("%s: %v", v.Name, err)
				continue
			}
			if got != v.Normalized {
				t.Errorf("%s normalized to %q, vector says %q", v.Name, got, v.Normalized)
			}
			if FormatRecoveryCode(got) != v.Display {
				t.Errorf("%s displayed as %q, vector says %q", v.Name, FormatRecoveryCode(got), v.Display)
			}
			b, err := RecoveryCodeSecret(v.Input)
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(b) != v.Secret {
				t.Errorf("%s decoded to %s, vector says %s", v.Name, hex.EncodeToString(b), v.Secret)
			}
			// Every spelling in the file is one code.
			if secret == "" {
				secret = v.Secret
			} else if v.Secret != secret {
				t.Errorf("%s decoded to a different code than the others", v.Name)
			}
		}
	})

	t.Run("recovery-wraps", func(t *testing.T) {
		for _, v := range doc.RecoveryWraps {
			blob := mustHex(t, v.Blob)
			got, err := UnwrapWithRecovery(v.Code, v.Holder, blob)
			if err != nil {
				t.Errorf("%s: the committed blob did not open: %v", v.Name, err)
				continue
			}
			if hex.EncodeToString(got[:]) != v.Private {
				t.Errorf("%s: opened to a different key", v.Name)
			}
			secret, err := RecoveryCodeSecret(v.Code)
			if err != nil {
				t.Fatal(err)
			}
			salt := vectorSaltFromHex(t, v.WrapSalt)
			priv := mustKey(t, v.Private)
			rebuilt, err := wrapSecret(secret, domainWrapRecovery, wrapKindRecovery, salt, "", v.Holder, priv[:])
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(rebuilt) != v.Blob {
				t.Errorf("%s: rebuilt to %s, vector says %s", v.Name, hex.EncodeToString(rebuilt), v.Blob)
			}
		}
	})
}
